import React, { useState } from 'react';
import { X, Lock, Mail, User as UserIcon, ShieldAlert, Phone, Calendar, CheckCircle, AlertTriangle, Eye, EyeOff } from 'lucide-react';
import { store } from '../../services/store';
import { supabase, isSupabaseConfigured } from '../../services/supabase';
import { audioManager } from '../../services/audioManager';
import { useTranslation } from '../../services/i18n';
import { AvatarSelectorModal, ANIMAL_AVATARS } from '../common/AvatarSelectorModal';

const COUNTRY_CODES = [
  { code: '+244', country: 'Angola 🇦🇴', flag: '🇦🇴' }, { code: '+351', country: 'Portugal 🇵🇹', flag: '🇵🇹' },
  { code: '+55', country: 'Brasil 🇧🇷', flag: '🇧🇷' }, { code: '+258', country: 'Moçambique 🇲🇿', flag: '🇲🇿' },
  { code: '+238', country: 'Cabo Verde 🇨🇻', flag: '🇨🇻' }, { code: '+239', country: 'São Tomé e Príncipe 🇸🇹', flag: '🇸🇹' },
  { code: '+245', country: 'Guiné-Bissau 🇬🇼', flag: '🇬🇼' }, { code: '+1', country: 'Estados Unidos / Canadá 🇺🇸', flag: '🇺🇸' },
  { code: '+34', country: 'Espanha 🇪🇸', flag: '🇪🇸' }, { code: '+33', country: 'França 🇫🇷', flag: '🇫🇷' }, { code: '+44', country: 'Reino Unido 🇬🇧', flag: '🇬🇧' },
];
interface AuthModalProps { isOpen: boolean; initialTab?: 'login' | 'register'; onClose: () => void; onSuccess: () => void; onOpenAdminLogin?: () => void; }
export const AuthModal: React.FC<AuthModalProps> = ({ isOpen, initialTab = 'login', onClose, onSuccess }) => {
  const { t } = useTranslation(); const [tab, setTab] = useState<'login' | 'register' | 'forgot'>(initialTab);
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [countryCode, setCountryCode] = useState('+244'); const [phone, setPhone] = useState(''); const [birthDate, setBirthDate] = useState(''); const [referralCodeInput, setReferralCodeInput] = useState('');
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [acceptedTerms, setAcceptedTerms] = useState(false); const [showPassword, setShowPassword] = useState(false); const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [selectedAvatar, setSelectedAvatar] = useState(ANIMAL_AVATARS[0].url); const [isAvatarModalOpen, setIsAvatarModalOpen] = useState(false); const [errorMsg, setErrorMsg] = useState(''); const [successMsg, setSuccessMsg] = useState(''); const [loading, setLoading] = useState(false);
  React.useEffect(() => { if (isOpen) { setTab(initialTab); setErrorMsg(''); setSuccessMsg(''); } }, [isOpen, initialTab]);
  const checkIsAdult = (v: string) => { if (!v) return false; const d = new Date(v); if (isNaN(d.getTime())) return false; const n = new Date(); let a = n.getFullYear() - d.getFullYear(); const m = n.getMonth() - d.getMonth(); if (m < 0 || (m === 0 && n.getDate() < d.getDate())) a--; return a >= 18; };
  const loadProfile = async (user: any, fallback: { name?: string; phone?: string; avatar?: string } = {}) => {
    const { data, error } = await supabase.rpc('get_my_profile'); if (error) throw new Error('Não foi possível carregar o perfil da conta.'); const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error('Perfil da conta não encontrado.');
    if (row.role === 'admin') throw new Error('Esta conta deve utilizar o Portal Admin.'); if (row.status && row.status !== 'active') throw new Error('A conta encontra-se inativa.'); await supabase.rpc('touch_my_login');
    return { id: user.id, name: row.name || fallback.name || user.user_metadata?.name || user.email?.split('@')[0] || 'Jogador', email: row.email || user.email || '', phone: row.phone || fallback.phone || '', avatar: row.avatar_url || fallback.avatar || user.user_metadata?.avatar_url || `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(user.email || user.id)}`, role: 'player' as const, status: 'active' as const, isVerified: Boolean(row.is_verified), verificationStatus: row.is_verified ? 'verified' as const : 'unverified' as const, referralCode: row.referral_code, referralCount: Number(row.referral_count || 0), referralEarnings: Number(row.referral_earnings || 0), createdAt: row.created_at || user.created_at || new Date().toISOString(), lastLoginAt: row.last_login_at || new Date().toISOString() };
  };
  if (!isOpen) return null;
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setErrorMsg(''); setSuccessMsg(''); if (!isSupabaseConfigured) { setErrorMsg('O serviço de autenticação não está configurado. Tente novamente mais tarde.'); return; } setLoading(true);
    try {
      if (tab === 'register') {
        if (!name.trim()) throw new Error('Nome de utilizador é obrigatório'); if (!email.includes('@')) throw new Error('Endereço de email inválido'); if (!phone.trim() || phone.replace(/\D/g, '').length < 6) throw new Error('Por favor introduza um contacto do WhatsApp válido'); if (!birthDate) throw new Error('Data de nascimento é obrigatória'); if (!checkIsAdult(birthDate)) throw new Error('Acesso restrito: Deve ter pelo menos 18 anos de idade para se registar.'); if (password.length < 6) throw new Error('A palavra-passe deve ter pelo menos 6 caracteres'); if (password !== confirmPassword) throw new Error('As palavras-passe não coincidem'); if (!acceptedTerms) throw new Error('Aceite os termos e condições');
        const fp = store.getDeviceFingerprint(); const anti = store.validateRegistrationAntiFraud({ email, phone: `${countryCode} ${phone}`, birthDate, deviceFingerprint: fp }); if (!anti.valid) throw new Error(anti.reason || 'Registo bloqueado por motivos de segurança.');
        const { data, error } = await supabase.auth.signUp({ email: email.trim().toLowerCase(), password, options: { data: { name: name.trim(), avatar_url: selectedAvatar, phone: `${countryCode} ${phone}`, birth_date: birthDate, device_fingerprint: fp, referral_code_input: referralCodeInput || null } } });
        if (error) throw error; if (!data.user) throw new Error('Não foi possível criar a conta.'); if (!data.session) { setSuccessMsg('Conta criada. Verifique o seu email para ativar a conta e depois entre com a sua palavra-passe.'); setTab('login'); return; }
        const u = await loadProfile(data.user, { name: name.trim(), phone: `${countryCode} ${phone}`, avatar: selectedAvatar }); store.setCurrentUser(u, referralCodeInput || undefined); audioManager.playNotification(); onSuccess(); onClose(); return;
      }
      if (tab === 'login') {
        if (!email || !password) throw new Error('Preencha o email e a palavra-passe'); if (email.toLowerCase().includes('admin')) throw new Error('Contas administrativas devem usar o Portal Admin dedicado.'); const { data, error } = await supabase.auth.signInWithPassword({ email: email.trim().toLowerCase(), password }); if (error) throw error; if (!data.user || !data.session) throw new Error('Não foi possível estabelecer uma sessão segura.'); const u = await loadProfile(data.user); store.setCurrentUser(u); audioManager.playNotification(); onSuccess(); onClose(); return;
      }
      if (!email) throw new Error('Insira o seu email'); const { error } = await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(), { redirectTo: `${window.location.origin}/#recover-password` }); if (error) throw error; setSuccessMsg('Instruções para redefinir a palavra-passe foram enviadas para o seu email.'); setTab('login');
    } catch (err: any) { console.error('[AuthModal]', err); setErrorMsg(err?.message || 'Não foi possível concluir a operação.'); } finally { setLoading(false); }
  };
  const input = 'w-full rounded-xl bg-slate-950/90 border border-slate-700/80 px-4 py-3 text-sm text-white placeholder:text-slate-600 outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-500/15';
  return <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto"><div className="w-full max-w-md bg-slate-900/95 border border-cyan-500/30 rounded-3xl p-6 sm:p-8 shadow-2xl shadow-cyan-950/50 relative">
    <button id="btn-close-auth" onClick={onClose} aria-label="Fechar" className="absolute top-5 right-5 p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition cursor-pointer"><X className="w-4 h-4" /></button>
    <div className="mb-5 pr-10"><div className="text-[10px] font-bold tracking-[0.3em] text-cyan-400 uppercase">SKY-BIRD</div><h2 className="mt-1 text-xl font-black text-white tracking-tight">{tab === 'register' ? 'Criar conta' : tab === 'forgot' ? 'Recuperar acesso' : 'Bem-vindo de volta'}</h2><p className="mt-1 text-xs text-slate-500">Acesso autenticado e protegido.</p></div>
    {tab !== 'forgot' && <div className="flex items-center gap-2 p-1 rounded-2xl bg-slate-950 border border-slate-800 mb-6"><button type="button" onClick={() => { setTab('login'); setErrorMsg(''); setSuccessMsg(''); }} className={`flex-1 py-2.5 rounded-xl text-xs font-bold tracking-wider transition cursor-pointer ${tab === 'login' ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30' : 'text-slate-400 hover:text-white'}`}>{t('nav.login', 'ENTRAR')}</button><button type="button" onClick={() => { setTab('register'); setErrorMsg(''); setSuccessMsg(''); }} className={`flex-1 py-2.5 rounded-xl text-xs font-bold tracking-wider transition cursor-pointer ${tab === 'register' ? 'bg-cyan-500 text-slate-950 shadow-md shadow-cyan-500/30' : 'text-slate-400 hover:text-white'}`}>CRIAR CONTA</button></div>}
    {(errorMsg || successMsg) && <div className={`mb-5 rounded-xl border px-3 py-3 text-xs flex gap-2 items-start ${errorMsg ? 'border-red-500/30 bg-red-500/10 text-red-200' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200'}`}>{errorMsg ? <AlertTriangle className="w-4 h-4 shrink-0" /> : <CheckCircle className="w-4 h-4 shrink-0" />}<span>{errorMsg || successMsg}</span></div>}
    <form onSubmit={handleSubmit} className="space-y-4">
      {tab === 'register' && <><label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Nome de utilizador</span><div className="relative"><UserIcon className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input className={`${input} pl-10`} value={name} onChange={e => setName(e.target.value)} placeholder="O seu nome" /></div></label><label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">WhatsApp</span><div className="flex gap-2"><select className="w-28 rounded-xl bg-slate-950 border border-slate-700 text-sm text-white px-2" value={countryCode} onChange={e => setCountryCode(e.target.value)}>{COUNTRY_CODES.map(c => <option key={c.code} value={c.code}>{c.flag} {c.code}</option>)}</select><div className="relative flex-1"><Phone className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input className={`${input} pl-10`} value={phone} onChange={e => setPhone(e.target.value)} placeholder="923 000 000" inputMode="tel" /></div></div></label><label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Data de nascimento</span><div className="relative"><Calendar className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input type="date" className={`${input} pl-10`} value={birthDate} onChange={e => setBirthDate(e.target.value)} /></div></label></>}
      <label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Endereço de E-mail</span><div className="relative"><Mail className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input type="email" autoComplete="email" className={`${input} pl-10`} value={email} onChange={e => setEmail(e.target.value)} placeholder="email@dominio.com" /></div></label>
      {tab !== 'forgot' && <><label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Palavra-passe</span><div className="relative"><Lock className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input type={showPassword ? 'text' : 'password'} autoComplete={tab === 'register' ? 'new-password' : 'current-password'} className={`${input} pl-10 pr-11`} value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" /><button type="button" onClick={() => setShowPassword(v => !v)} className="absolute right-3 top-3 text-slate-500 hover:text-white" aria-label="Mostrar ou ocultar palavra-passe">{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></label>{tab === 'register' && <label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Confirmar palavra-passe</span><div className="relative"><Lock className="absolute left-3 top-3.5 w-4 h-4 text-slate-500" /><input type={showConfirmPassword ? 'text' : 'password'} autoComplete="new-password" className={`${input} pl-10 pr-11`} value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} placeholder="••••••••" /><button type="button" onClick={() => setShowConfirmPassword(v => !v)} className="absolute right-3 top-3 text-slate-500 hover:text-white" aria-label="Mostrar ou ocultar confirmação">{showConfirmPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></label>}</>}
      {tab === 'register' && <><label className="block"><span className="block mb-1.5 text-xs font-semibold text-slate-300">Código de referência <span className="text-slate-600">(opcional)</span></span><input className={input} value={referralCodeInput} onChange={e => setReferralCodeInput(e.target.value.toUpperCase())} placeholder="EX: SB123456" /></label><div className="rounded-xl border border-slate-800 bg-slate-950/60 p-3 flex items-center justify-between"><div><div className="text-xs font-semibold text-white">Avatar</div><div className="text-[10px] text-slate-500">Escolha a sua identidade</div></div><button type="button" onClick={() => setIsAvatarModalOpen(true)} className="text-xs text-cyan-400 hover:text-cyan-300 font-bold">SELECIONAR</button></div><label className="flex items-start gap-3 text-xs text-slate-400 cursor-pointer"><input type="checkbox" checked={acceptedTerms} onChange={e => setAcceptedTerms(e.target.checked)} className="mt-0.5 accent-cyan-500" /><span>Confirmo que tenho 18 anos ou mais e aceito os termos e condições.</span></label></>}
      {tab === 'login' && <button type="button" onClick={() => { setTab('forgot'); setErrorMsg(''); setSuccessMsg(''); }} className="text-xs text-cyan-400 hover:text-cyan-300">Esqueci a palavra-passe</button>}
      <button type="submit" disabled={loading} className="w-full py-3.5 rounded-xl bg-gradient-to-r from-cyan-400 to-blue-600 hover:from-cyan-300 hover:to-blue-500 disabled:opacity-60 disabled:cursor-not-allowed text-slate-950 font-black text-sm tracking-wide shadow-lg shadow-cyan-900/30 transition">{loading ? 'A PROCESSAR…' : tab === 'register' ? 'CRIAR CONTA' : tab === 'forgot' ? 'ENVIAR INSTRUÇÕES' : 'ENTRAR AGORA'}</button>
    </form><div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-slate-600"><ShieldAlert className="w-3.5 h-3.5" /> AUTENTICAÇÃO SEGURA • SKY-BIRD</div>{tab === 'forgot' && <button type="button" onClick={() => { setTab('login'); setErrorMsg(''); setSuccessMsg(''); }} className="mt-3 w-full text-xs text-slate-500 hover:text-white">← Voltar ao login</button>}
    <AvatarSelectorModal isOpen={isAvatarModalOpen} onClose={() => setIsAvatarModalOpen(false)} selectedAvatar={selectedAvatar} onSelect={(avatar: string) => { setSelectedAvatar(avatar); setIsAvatarModalOpen(false); }} />
  </div></div>;
};
